//------------------------------------------------------------------------------
// <auto-generated>
//
// Manual changes to this file may cause unexpected behavior in your application.
// Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace BBCoders.Example.DataModels
{
    public class GetSheduleAsync2ResponseModel
    {
        public Int32 Value_0 { get; set; }
        public GetSheduleAsync2ResponseModel()
        {
        }
    }
}
