//------------------------------------------------------------------------------
// <auto-generated>
//
// Manual changes to this file may cause unexpected behavior in your application.
// Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace BBCoders.Example.DataModels
{
    public class GetScheduleSitesByLocationResponseModel
    {
        public GetScheduleSitesByLocationResponseModel()
        {
            ScheduleSite = new ScheduleSiteModel();
        }
        public ScheduleSiteModel ScheduleSite { get; set; }
        public class ScheduleSiteModel
        {
            public Int64 Id { get; set; }
            public Boolean IsActive { get; set; }
            public String Name { get; set; }
            public Guid ScheduleSiteId { get; set; }
            public ScheduleSiteModel()
            {
            }
        }
    }
}
