//------------------------------------------------------------------------------
// <auto-generated>
//
// Manual changes to this file may cause unexpected behavior in your application.
// Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace BBCoders.Example.DataModels
{
    public class ScheduleModel
    {
        public Int64 Id { get; set; }
        public Int64? ActionId { get; set; }
        public Int64 CreatedById { get; set; }
        public DateTime CreatedDate { get; set; }
        public Int64? FingerPrintId { get; set; }
        public Int64 LastUpdatedById { get; set; }
        public DateTime LastUpdatedDate { get; set; }
        public DateTime ScheduleDate { get; set; }
        public Guid ScheduleId { get; set; }
        public Int64 ScheduleSiteId { get; set; }
        public ScheduleModel()
        {
        }
    }
}
