//------------------------------------------------------------------------------
// <auto-generated>
//
// Manual changes to this file may cause unexpected behavior in your application.
// Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace BBCoders.Example.DataModels
{
    public class StateModel
    {
        public Int64 Id { get; set; }
        public String Name { get; set; }
        public Guid StateId { get; set; }
        public StateModel()
        {
        }
    }
}
