// using System.Collections.Generic;
// using BBCoders.Commons.QueryGenerator;
// using BBCoders.Commons.QueryGeneratorTool.Models;
// using Microsoft.EntityFrameworkCore.Infrastructure;
// using Microsoft.EntityFrameworkCore.Metadata;

// namespace BBCoders.Commons.QueryGeneratorTool.Services.OperationGenerator
// {
//     public class JavaScriptOperationGenerator : BaseOperationGenerator
//     {
//         public JavaScriptOperationGenerator(SqlOperationGeneratorDependencies dependencies, QueryOptions options, List<ITable> tables, List<SqlModel> sqlModels) : base(dependencies, options, tables, sqlModels)
//         {
//         }

//         protected override void GenerateLanguageMethod(IndentedStringBuilder builder, MethodOperation methodOperation)
//         {
//             throw new System.NotImplementedException();
//         }
//         protected override void GenerateLanguageModel(IndentedStringBuilder builder, ClassModel classModel)
//         {
//             GenerateComment(builder);
//             GenerateModel(builder, classModel, true);
//         }

//         private void GenerateModel(IndentedStringBuilder builder, ClassModel classModel, bool declareClass)
//         {
//             if (declareClass)
//             {
//                 builder.AppendLine($"export interface {classModel.Name}");
//             }
//             else
//             {
//                 builder.AppendLine(classModel.Name + ": ");
//             }

//             builder.AppendLine("{");
//             using (builder.Indent())
//             {
//                 foreach (var property in classModel.Properties)
//                 {
//                     var typeName = property.IsNullable ? property.Name + "?" : property.Name;
//                     builder.AppendLine($"{typeName}: {property.TypeName};");
//                 }

//                 foreach (var nestedModel in classModel.NestedClass)
//                 {
//                     GenerateModel(builder, nestedModel, false);
//                 }
//             }
//             builder.AppendLine("}");
//         }
//         private void GenerateComment(IndentedStringBuilder builder)
//         {
//             builder.AppendLine("//------------------------------------------------------------------------------");
//             builder.AppendLine("// <auto-generated>");
//             builder.AppendLine("//");
//             builder.AppendLine("// Manual changes to this file may cause unexpected behavior in your application.");
//             builder.AppendLine("// Manual changes to this file will be overwritten if the code is regenerated.");
//             builder.AppendLine("// </auto-generated>");
//             builder.AppendLine("//------------------------------------------------------------------------------");
//         }
//     }
// }