//------------------------------------------------------------------------------
// <auto-generated>
//
// Manual changes to this file may cause unexpected behavior in your application.
// Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace BBCoders.Example.DataServices
{
    public class FingerprintKey
    {
        public Int64 Id { get; set; }
    }
    public class FingerprintModel
    {
        public Int64 Id { get; set; }
        public Int64 CreatedById { get; set; }
        public DateTime CreatedDate { get; set; }
        public DateTime? ExpirationDate { get; set; }
        public Byte[] FingerprintId { get; set; }
        public Boolean IsActive { get; set; }
        public Int64 LastUpdatedById { get; set; }
        public Int64 NmlsId { get; set; }
        public DateTime? RenewalDate { get; set; }
        public Int64 StateId { get; set; }
        public DateTime UpdatedDate { get; set; }
    }
    public class GetFingerprintByGuidsRequestModel
    {
        public List<Byte[]> test { get; set; }
    }
    public class GetFingerprintByGuidsResponseModel
    {
        public FingerprintProjection Fingerprint { get; set; }
        public GetFingerprintByGuidsResponseModel()
        {
            Fingerprint = new FingerprintProjection();
        }
        public class FingerprintProjection
        {
            public Int64 Id { get; set; }
            public Int64 CreatedById { get; set; }
            public DateTime CreatedDate { get; set; }
            public DateTime? ExpirationDate { get; set; }
            public Byte[] FingerprintId { get; set; }
            public Boolean IsActive { get; set; }
            public Int64 LastUpdatedById { get; set; }
            public Int64 NmlsId { get; set; }
            public DateTime? RenewalDate { get; set; }
            public Int64 StateId { get; set; }
            public DateTime UpdatedDate { get; set; }
        }
    }
    public class GetFingerprintsByIdRequestModel
    {
        public List<Int64> test { get; set; }
    }
    public class GetFingerprintsByIdResponseModel
    {
        public FingerprintProjection Fingerprint { get; set; }
        public GetFingerprintsByIdResponseModel()
        {
            Fingerprint = new FingerprintProjection();
        }
        public class FingerprintProjection
        {
            public Int64 Id { get; set; }
            public Byte[] FingerprintId { get; set; }
            public Boolean IsActive { get; set; }
        }
    }
    public class GetFingerprintByStateIdRequestModel
    {
        public Boolean active { get; set; }
        public List<Byte[]> fingerprintId { get; set; }
        public List<Byte[]> stateId { get; set; }
    }
    public class GetFingerprintByStateIdResponseModel
    {
        public FingerprintProjection Fingerprint { get; set; }
        public StateProjection State { get; set; }
        public GetFingerprintByStateIdResponseModel()
        {
            Fingerprint = new FingerprintProjection();
            State = new StateProjection();
        }
        public class FingerprintProjection
        {
            public Int64 Id { get; set; }
            public Int64 CreatedById { get; set; }
            public DateTime CreatedDate { get; set; }
            public DateTime? ExpirationDate { get; set; }
            public Byte[] FingerprintId { get; set; }
            public Boolean IsActive { get; set; }
            public Int64 LastUpdatedById { get; set; }
            public Int64 NmlsId { get; set; }
            public DateTime? RenewalDate { get; set; }
            public Int64 StateId { get; set; }
            public DateTime UpdatedDate { get; set; }
        }
        public class StateProjection
        {
            public Int64 Id { get; set; }
            public String Name { get; set; }
            public Byte[] StateId { get; set; }
        }
    }
}
