//------------------------------------------------------------------------------
// <auto-generated>
//
// Manual changes to this file may cause unexpected behavior in your application.
// Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace BBCoders.Example.DataServices
{
    public class GetSheduleActionResponseModel
    {
        public GetSheduleActionResponseModel()
        {
            Schedule = new ScheduleModel();
        }
        public ScheduleModel Schedule { get; set; }
        public class ScheduleModel
        {
            public Int64? action { get; set; }
            public Int64 id { get; set; }
            public Byte[] schedule_id { get; set; }
            public ScheduleModel()
            {
            }
        }
    }
}
