//------------------------------------------------------------------------------
// <auto-generated>
//
// Manual changes to this file may cause unexpected behavior in your application.
// Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace BBCoders.Example.DataServices
{
    public class GetSheduleAsyncResponseModel
    {
        public GetSheduleAsyncResponseModel()
        {
            Schedule = new ScheduleModel();
            ScheduleSite = new ScheduleSiteModel();
            Fingerprint = new FingerprintModel();
            State = new StateModel();
        }
        public ScheduleModel Schedule { get; set; }
        public class ScheduleModel
        {
            public Int64 Id { get; set; }
            public Int64? ActionId { get; set; }
            public Int64 CreatedById { get; set; }
            public DateTime CreatedDate { get; set; }
            public Int64? FingerPrintId { get; set; }
            public Int64 LastUpdatedById { get; set; }
            public DateTime LastUpdatedDate { get; set; }
            public DateTime ScheduleDate { get; set; }
            public Byte[] ScheduleId { get; set; }
            public Int64 ScheduleSiteId { get; set; }
            public ScheduleModel()
            {
            }
        }
        public ScheduleSiteModel ScheduleSite { get; set; }
        public class ScheduleSiteModel
        {
            public Int64 Id { get; set; }
            public Boolean IsActive { get; set; }
            public String Name { get; set; }
            public Byte[] ScheduleSiteId { get; set; }
            public ScheduleSiteModel()
            {
            }
        }
        public FingerprintModel Fingerprint { get; set; }
        public class FingerprintModel
        {
            public Int64? Id { get; set; }
            public Int64? CreatedById { get; set; }
            public DateTime? CreatedDate { get; set; }
            public DateTime? ExpirationDate { get; set; }
            public Byte[] FingerprintId { get; set; }
            public Boolean? IsActive { get; set; }
            public Int64? LastUpdatedById { get; set; }
            public Int64? NmlsId { get; set; }
            public DateTime? RenewalDate { get; set; }
            public Int64? StateId { get; set; }
            public DateTime? UpdatedDate { get; set; }
            public FingerprintModel()
            {
            }
        }
        public StateModel State { get; set; }
        public class StateModel
        {
            public Int64? Id { get; set; }
            public String Name { get; set; }
            public Byte[] StateId { get; set; }
            public StateModel()
            {
            }
        }
    }
}
