//------------------------------------------------------------------------------
// <auto-generated>
//
// Manual changes to this file may cause unexpected behavior in your application.
// Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace BBCoders.Example.DataServices
{
    public class GetScheduleSitesByLocationRequestModel
    {
        public String location { get; set; }
        public GetScheduleSitesByLocationRequestModel()
        {
        }
    }
}
