//------------------------------------------------------------------------------
// <auto-generated>
//
// Manual changes to this file may cause unexpected behavior in your application.
// Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace BBCoders.Example.DataServices
{
    public class ScheduleSiteModel
    {
        public Int64 Id { get; set; }
        public Boolean IsActive { get; set; }
        public String Name { get; set; }
        public Byte[] ScheduleSiteId { get; set; }
    }
    public class GetScheduleSitesByLocationRequestModel
    {
        public String location { get; set; }
    }
    public class GetScheduleSitesByLocationResponseModel
    {
        public ScheduleSiteProjection ScheduleSite { get; set; }
        public GetScheduleSitesByLocationResponseModel()
        {
            ScheduleSite = new ScheduleSiteProjection();
        }
        public class ScheduleSiteProjection
        {
            public Int64 Id { get; set; }
            public Boolean IsActive { get; set; }
            public String Name { get; set; }
            public Byte[] ScheduleSiteId { get; set; }
        }
    }
    public class GetSheduleSiteStatusRequestModel
    {
        public Byte[] id { get; set; }
    }
    public class GetSheduleSiteStatusResponseModel
    {
        public ScheduleSiteProjection ScheduleSite { get; set; }
        public GetSheduleSiteStatusResponseModel()
        {
            ScheduleSite = new ScheduleSiteProjection();
        }
        public class ScheduleSiteProjection
        {
            public Int64 Id { get; set; }
            public Boolean IsActive { get; set; }
            public String Name { get; set; }
            public Byte[] ScheduleSiteId { get; set; }
        }
    }
}
