//------------------------------------------------------------------------------
// <auto-generated>
//
// Manual changes to this file may cause unexpected behavior in your application.
// Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

namespace BBCoders.Example.DataServices
{
    public class ScheduleSiteSelectModel
    {
        public Int64 Id { get; set; }
        public Boolean IsActive { get; set; }
        public String Name { get; set; }
        public Byte[] ScheduleSiteId { get; set; }
    }
    public class ScheduleSiteInsertModel
    {
        public Boolean IsActive { get; set; }
        public String Name { get; set; }
        public Byte[] ScheduleSiteId { get; set; }
    }
    public class ScheduleSiteUpdateModel
    {
        public Int64 Id { get; set; }
        public Boolean IsActive { get; set; }
        public String Name { get; set; }
        public Byte[] ScheduleSiteId { get; set; }
    }
    public class ScheduleSiteDeleteModel
    {
        public Int64 Id { get; set; }
    }
    public class GetshedulesitestatusRequestModel
    {
        public Byte[] id { get; set; }
    }
    public class GetshedulesitestatusResponseModel
    {
        public Int64 Id { get; set; }
        public Boolean IsActive { get; set; }
        public String Name { get; set; }
        public Byte[] ScheduleSiteId { get; set; }
    }
}
