//------------------------------------------------------------------------------
// <auto-generated>
//
// Manual changes to this file may cause unexpected behavior in your application.
// Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace BBCoders.Example.DataServices
{
    public class StateModel
    {
        public Int64 Id { get; set; }
        public String? Name { get; set; }
        public Byte[] StateId { get; set; }
    }
}
